### ISSUE TITLE
Bluebird promise creation warning

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/oddcast#21]
https://github.com/oddnetworks/oddworks/issues/17

```
Warning: a promise was created in a handler but was not returned from it
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at RequestChannel.utils.extend.executeHandler (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/oddcast/lib/channel.js:171:10)
    at InprocessTransport.onMessage [as handler] (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/oddcast/lib/channel.js:134:18)
    at InprocessTransport.utils.extend.write (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/oddcast/lib/inprocess_transport.js:26:16)
    at RequestChannel.utils.extend.request (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/oddcast/lib/request_channel.js:23:20)
    at Bus.utils.extend.query (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/oddcast/lib/bus.js:67:24)
    at /Users/blainsmith/Projects/oddnetworks/oddworks/services/catalog/index.js:35:8
    at Layer.handle [as handle_request] (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/layer.js:95:5)
    at /Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:46:12)
From previous event:
    at /Users/blainsmith/Projects/oddnetworks/oddworks/services/identity/index.js:34:6
    at Layer.handle [as handle_request] (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:312:13)
    at /Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:271:10)
    at compression (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/compression/index.js:218:5)
    at Layer.handle [as handle_request] (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:312:13)
    at /Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:271:10)
    at requestSession (/Users/blainsmith/Projects/oddnetworks/oddworks/middleware/request-session.js:10:2)
    at Layer.handle [as handle_request] (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:312:13)
    at /Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:271:10)
    at requestContentType (/Users/blainsmith/Projects/oddnetworks/oddworks/middleware/request-accept.js:22:2)
```

**Comment by kixxauth** [comment]
These errors are caused by user applications that don't return values from promise handlers.

This commit helps reduce the problem in oddcast code c75e9c047c6336e3e6a177cdbe8540096f961d53
